version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: gnuradio/pelican:latest
    steps:
      - run: 'eval $(ssh-agent -s)'
      - add_ssh_keys:
          fingerprints:
            - "f1:bd:c1:e8:89:71:77:b8:4c:48:0d:9c:f9:9e:85:2f"
      - run: 'mkdir -p ~/.ssh'
      - run: 'chmod 700 ~/.ssh'
      - run: 'echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts'
      - run: 'chmod 644 ~/.ssh/known_hosts'
      - checkout
      - run: 'pelican --version'
      - run: 'pelican --relative-urls content/ -o public/ -s pelicanconf.py'
      - run: 'echo $(date +%Y.%m.%d)'
      - run: 'tar -cz public | ssh $SSH_USER@$SSH_HOST "mkdir -p /www/$(date +%Y.%m.%d); cd /www/$(date +%Y.%m.%d); tar --strip-components=1 -xz; rm /www/live; cd /www; ln -sf $(date +%Y.%m.%d) live;"'
